// Generated by CoffeeScript 2.6.1
// auto-import.test.coffee
var dumpfile, hSymbols, rootDir, simple;

import assert from 'assert';

import {
  UnitTester
} from '@jdeighan/unit-tester';

import {
  undef,
  words,
  isArray
} from '@jdeighan/coffee-utils';

import {
  mydir,
  mkpath
} from '@jdeighan/coffee-utils/fs';

import {
  debug,
  setDebugging
} from '@jdeighan/coffee-utils/debug';

import {
  log
} from '@jdeighan/coffee-utils/log';

import {
  joinBlocks
} from '@jdeighan/coffee-utils/block';

import {
  convertCoffee,
  brewCoffeeStr
} from '@jdeighan/string-input/coffee';

import {
  buildImportList,
  getAvailSymbols
} from '@jdeighan/string-input/symbols';

rootDir = process.env.DIR_ROOT = mydir(import.meta.url);

simple = new UnitTester();

convertCoffee(false);

dumpfile = "c:/Users/johnd/string-input/test/ast.txt";

// ----------------------------------------------------------------------------
// --- make sure it's using the testing .symbols file
hSymbols = getAvailSymbols(rootDir);

simple.equal(23, hSymbols, {
  fs: {
    lib: 'fs',
    isDefault: true
  },
  exists: {
    lib: 'fs'
  },
  readFile: {
    lib: 'fs'
  },
  barf: {
    lib: '@jdeighan/coffee-utils/fs'
  },
  logger: {
    lib: '@jdeighan/coffee-utils/log',
    src: 'log'
  },
  mkpath: {
    lib: '@jdeighan/coffee-utils/fs'
  },
  mydir: {
    lib: '@jdeighan/coffee-utils/fs'
  },
  say: {
    lib: '@jdeighan/coffee-utils'
  },
  slurp: {
    lib: '@jdeighan/coffee-utils/fs'
  },
  undef: {
    lib: '@jdeighan/coffee-utils'
  }
});

// ----------------------------------------------------------------------------
(function() {
  var lImports, text;
  text = `x = 42
say "Answer is 42"`;
  lImports = ["import {say} from '@jdeighan/coffee-utils'", "import {slurp} from '#jdeighan/coffee-utils/fs'"];
  return simple.equal(46, joinBlocks(...lImports, text), `import {say} from '@jdeighan/coffee-utils'
import {slurp} from '#jdeighan/coffee-utils/fs'
x = 42
say "Answer is 42"`);
})();

// ----------------------------------------------------------------------------
(function() {
  var lNeeded;
  lNeeded = words('say undef logger slurp barf fs');
  return simple.equal(58, buildImportList(lNeeded, rootDir), ["import fs from 'fs'", "import {say,undef} from '@jdeighan/coffee-utils'", "import {slurp,barf} from '@jdeighan/coffee-utils/fs'", "import {log as logger} from '@jdeighan/coffee-utils/log'"]);
})();

// ----------------------------------------------------------------------------
(function() {
  var code, newcode;
  code = `# --- temp.cielo
if fs.existsSync('file.txt')
	logger "file exists"`;
  newcode = brewCoffeeStr(code);
  return simple.equal(81, newcode, `import fs from 'fs'
import {log as logger} from '@jdeighan/coffee-utils/log'
if fs.existsSync('file.txt')
	logger "file exists"`);
})();

// ---------------------------------------------------------------------------
