// Generated by CoffeeScript 2.5.1
// CoffeeMapper.test.coffee
var CoffeeMapperTester, tester;

import {
  AvaTester
} from '@jdeighan/ava-tester';

import {
  undef,
  say,
  setUnitTesting
} from '@jdeighan/coffee-utils';

import {
  StringInput
} from '@jdeighan/string-input';

import {
  CoffeeMapper
} from '@jdeighan/string-input/convert';

// NOTE: In unit tests, CoffeeScript is NOT converted
//       to JavaScript
setUnitTesting(true);

// ---------------------------------------------------------------------------
CoffeeMapperTester = class CoffeeMapperTester extends AvaTester {
  transformValue(text) {
    var oInput;
    oInput = new CoffeeMapper(text);
    return oInput.get();
  }

};

tester = new CoffeeMapperTester();

// ---------------------------------------------------------------------------
// --- Test basic mapping
tester.equal(27, `x = 23
if x > 10
	console.log "OK"`, `x = 23`);

// ---------------------------------------------------------------------------
// --- Test live assignment
tester.equal(38, `x <== 2 * y
if x > 10
	console.log "OK"`, `\`$: x = 2 * y\``);

// ---------------------------------------------------------------------------
// --- Test live execution
(function() {
  var count;
  count = undef;
  return tester.equal(51, `<== console.log "Count is \#{count}"
if x > 10
	console.log "OK"`, `\`$: console.log "Count is \#{count}"\``);
})();

// ---------------------------------------------------------------------------
// --- Test live execution of a block
(function() {
  var count;
  count = undef;
  return tester.equal(65, `<==
	double = 2 * count
	console.log "Count is \#{count}"
if x > 10
	console.log "OK"`, `\`\`\`
$: {
	double = 2 * count
	console.log "Count is \#{count}"
	}
\`\`\``);
})();

// ---------------------------------------------------------------------------
// --- Test live execution of a block when NOT unit testing
(function() {
  var count;
  setUnitTesting(false);
  count = undef;
  tester.equal(85, `<==
	double = 2 * count
	console.log "Count is \#{count}"
if x > 10
	console.log "OK"`, `\`\`\`
$: {
	var double;
	double = 2 * count;
	console.log(\`Count is \${count}\`);
	}
\`\`\``);
  return setUnitTesting(true);
})();

// ---------------------------------------------------------------------------
