// Generated by CoffeeScript 2.6.1
// markdown.test.coffee
var MarkdownTester, root, simple, tester;

import {
  undef
} from '@jdeighan/coffee-utils';

import {
  mydir
} from '@jdeighan/coffee-utils/fs';

import {
  UnitTester
} from '@jdeighan/coffee-utils/test';

import {
  hPrivEnv
} from '@jdeighan/coffee-utils/privenv';

import {
  markdownify
} from '@jdeighan/string-input/markdown';

root = hPrivEnv.DIR_ROOT = mydir(import.meta.url);

hPrivEnv.DIR_DATA = `${root}/data hPrivEnv.DIR_MARKDOWN = `;

simple = new UnitTester();

// ---------------------------------------------------------------------------
MarkdownTester = class MarkdownTester extends UnitTester {
  transformValue(text) {
    return markdownify(text);
  }

};

tester = new MarkdownTester();

// ---------------------------------------------------------------------------
(function() {
  tester.equal(31, `title
=====`, `<h1>title</h1>`);
  tester.equal(38, `title
-----`, `<h2>title</h2>`);
  tester.equal(45, `this is **bold** text`, `<p>this is <strong>bold</strong> text</p>`);
  return tester.equal(51, `\`\`\`javascript
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: null,
			})
\`\`\``, `<pre><code class="language-javascript"> adapter: adapter(&lbrace;
pages: &#39;build&#39;,
assets: &#39;build&#39;,
fallback: null,
&rbrace;)
</code></pre>`);
})();
