// Generated by CoffeeScript 2.5.1
// code_utils.coffee
var indexOf = [].indexOf;

import {
  strict as assert
} from 'assert';

import CoffeeScript from 'coffeescript';

import {
  log,
  undef,
  pass,
  croak,
  isEmpty,
  nonEmpty,
  isComment,
  isString,
  unitTesting,
  escapeStr,
  firstLine,
  isHash,
  arrayToString,
  deepCopy
} from '@jdeighan/coffee-utils';

import {
  joinBlocks
} from '@jdeighan/coffee-utils/block';

import {
  slurp,
  barf,
  mydir,
  pathTo
} from '@jdeighan/coffee-utils/fs';

import {
  splitLine
} from '@jdeighan/coffee-utils/indent';

import {
  debug,
  debugging,
  startDebugging,
  endDebugging
} from '@jdeighan/coffee-utils/debug';

import {
  PLLParser
} from '@jdeighan/string-input';

import {
  ASTWalker
} from '@jdeighan/string-input/tree';

import {
  tamlStringify
} from '@jdeighan/string-input/convert';

// ---------------------------------------------------------------------------
export var prependImports = function(text, lImports) {
  var stmt;
  if (!unitTesting) {
    lImports = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = lImports.length; i < len; i++) {
        stmt = lImports[i];
        results.push(`${stmt};`);
      }
      return results;
    })();
  }
  return joinBlocks(...lImports, text);
};

// ---------------------------------------------------------------------------
export var mergeNeededSymbols = function(hAllNeeded, hNeeded) {
  var i, j, len, len1, lib, ref, ref1, sym;
  ref = Object.keys(hNeeded);
  //  both are: { <lib>: [ <symbol>, ...], ...}
  for (i = 0, len = ref.length; i < len; i++) {
    lib = ref[i];
    if (hAllNeeded[lib] != null) {
      ref1 = hNeeded[lib];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        sym = ref1[j];
        if (indexOf.call(hAllNeeded[lib], sym) < 0) {
          hAllNeeded[lib].push(sym);
        }
      }
    } else {
      hAllNeeded[lib] = deepCopy(hNeeded[lib]);
    }
  }
};

// ---------------------------------------------------------------------------
export var getNeededSymbols = function(code, hOptions = {}) {
  var hAvailSymbols, hMissing, hNeeded, i, len, lib, ref, sym;
  // --- Valid options:
  //        dumpfile: <filepath>   - where to dump ast
  // --- returns { <lib>: [ <symbol>, ... ], ... }
  debug("enter getNeededSymbols()");
  hMissing = getMissingSymbols(code, hOptions);
  if (isEmpty(hMissing)) {
    debug("return {} from getNeededSymbols() - no missing symbols");
    return {};
  }
  hAvailSymbols = getAvailSymbols();
  if (isEmpty(hAvailSymbols)) {
    debug("return {} from getNeededSymbols() - no avail symbols");
    return {};
  }
  hNeeded = {}; // { <lib>: [ <symbol>, ...], ...}
  ref = Object.keys(hMissing);
  for (i = 0, len = ref.length; i < len; i++) {
    sym = ref[i];
    if (lib = hAvailSymbols[sym]) {
      if (hNeeded[lib]) {
        hNeeded[lib].push(sym);
      } else {
        hNeeded[lib] = [sym];
      }
    }
  }
  return hNeeded;
};

// ---------------------------------------------------------------------------
export var buildImportList = function(hNeeded) {
  var i, lImports, len, lib, ref, symbols;
  lImports = [];
  ref = Object.keys(hNeeded);
  for (i = 0, len = ref.length; i < len; i++) {
    lib = ref[i];
    symbols = hNeeded[lib].join(',');
    lImports.push(`import {${symbols}} from '${lib}'`);
  }
  return lImports;
};

// ---------------------------------------------------------------------------
export var getNeededImports = function(code, hOptions = {}) {
  var hNeeded, i, lImports, len, lib, ref, symbols;
  // --- Valid options:
  //        dumpfile: <filepath>   - where to dump ast
  // --- returns lImports
  debug("enter getNeededImports()");
  hNeeded = getNeededSymbols(code, hOptions);
  lImports = [];
  ref = Object.keys(hNeeded);
  for (i = 0, len = ref.length; i < len; i++) {
    lib = ref[i];
    symbols = hNeeded[lib].join(',');
    lImports.push(`import {${symbols}} from '${lib}'`);
  }
  debug("return from getNeededImports()");
  return lImports;
};

// ---------------------------------------------------------------------------
export var getMissingSymbols = function(code, hOptions = {}) {
  var ast, err, hMissingSymbols, walker;
  // --- Valid options:
  //        dumpfile: <filepath>   - where to dump ast
  debug("enter getMissingSymbols()");
  try {
    debug(code, "COMPILE CODE (in getMissingSymbols):");
    ast = CoffeeScript.compile(code, {
      ast: true
    });
    assert(ast != null, "getMissingSymbols(): ast is empty");
  } catch (error) {
    err = error;
    croak(err, code, 'CODE (in getMissingSymbols)');
  }
  walker = new ASTWalker(ast);
  hMissingSymbols = walker.getMissingSymbols();
  if (hOptions.dumpfile) {
    barf(hOptions.dumpfile, "AST:\n" + tamlStringify(walker.ast));
  }
  debug("return from getMissingSymbols()");
  return hMissingSymbols;
};

// ---------------------------------------------------------------------------
// export to allow unit testing
export var getAvailSymbols = function() {
  var SymbolParser, body, contents, filepath, hItem, hSymbols, i, j, k, len, len1, len2, lib, ref, searchFromDir, sym, tree;
  debug("enter getAvailSymbols()");
  searchFromDir = process.env.DIR_SYMBOLS || mydir(import.meta.url);
  debug(`search for .symbols from '${searchFromDir}'`);
  filepath = pathTo('.symbols', searchFromDir, 'up');
  if (filepath == null) {
    return {};
  }
  debug(`.symbols file found at '${filepath}'`);
  contents = slurp(filepath);
  SymbolParser = class SymbolParser extends PLLParser {
    mapString(line, level) {
      if (level === 0) {
        return line;
      } else if (level === 1) {
        return line.split(/\s+/).filter(function(s) {
          return nonEmpty(s);
        });
      } else {
        return croak(`Bad .symbols file - level = ${level}`);
      }
    }

  };
  tree = new SymbolParser(contents).getTree();
  hSymbols = {}; // { <symbol>: <lib>, ... }
  for (i = 0, len = tree.length; i < len; i++) {
    ({
      node: lib,
      body
    } = tree[i]);
    for (j = 0, len1 = body.length; j < len1; j++) {
      hItem = body[j];
      ref = hItem.node;
      for (k = 0, len2 = ref.length; k < len2; k++) {
        sym = ref[k];
        assert(hSymbols[sym] == null, `dup symbol: '${sym}'`);
        hSymbols[sym] = lib;
      }
    }
  }
  debug("return from getAvailSymbols()");
  return hSymbols;
};
