// Generated by CoffeeScript 2.7.0
// debar.coffee
var DeBarMapper;

import {
  undef,
  pass,
  assert,
  isEmpty,
  nonEmpty,
  replaceVars
} from '@jdeighan/coffee-utils';

import {
  indented
} from '@jdeighan/coffee-utils/indent';

import {
  Mapper
} from '@jdeighan/mapper';

// ---------------------------------------------------------------------------
export var debar = function(block, hVars = {}) {
  var mapper;
  // --- returns an array of blocks
  mapper = new DeBarMapper(block, hVars);
  return mapper.getBlock();
};

// ---------------------------------------------------------------------------
DeBarMapper = class DeBarMapper extends Mapper {
  constructor(content, hMyVars) {
    assert(nonEmpty(content), "DeBarMapper(): empty content");
    super(content, 'debar');
    this.hMyVars = hMyVars;
  }

  // ..........................................................
  mapLine(line, level) {
    var _, lMatches, replaced, tail;
    lMatches = line.match(/^\s*(?:\#|\/\/)\s+\|\|(\d+)?\|\|\s*(.*)$/); // allow both CoffeeScript and JavaScript style
    if (!lMatches) {
      return line;
    }
    [_, level, tail] = lMatches;
    replaced = replaceVars(tail, this.hMyVars);
    if (isEmpty(replaced)) {
      return undef;
    } else if (level) {
      return indented(replaced, parseInt(level));
    } else {
      return replaced;
    }
  }

};
