// Generated by CoffeeScript 2.6.1
// JavaScriptBuiltins.coffee

// ---------------------------------------------------------------------------
var hJSBuiltins;

hJSBuiltins = {
  parseInt: true,
  process: true,
  JSON: true,
  import: true
};

// ---------------------------------------------------------------------------
export var isBuiltin = function(sym) {
  if (hJSBuiltins[sym] != null) {
    return true;
  } else {
    return false;
  }
};
