// Generated by CoffeeScript 2.7.0
// markdown.coffee
var convert, stripComments;

import {
  marked
} from 'marked';

import {
  assert,
  OL,
  nonEmpty,
  isComment
} from '@jdeighan/coffee-utils';

import {
  debug
} from '@jdeighan/coffee-utils/debug';

import {
  blockToArray
} from '@jdeighan/coffee-utils/block';

import {
  undented
} from '@jdeighan/coffee-utils/indent';

import {
  svelteHtmlEsc
} from '@jdeighan/coffee-utils/svelte';

convert = true;

// ---------------------------------------------------------------------------
export var convertMarkdown = function(flag) {
  convert = flag;
};

// ---------------------------------------------------------------------------
stripComments = function(block) {
  var i, lLines, len, line, ref;
  lLines = [];
  ref = blockToArray(block);
  for (i = 0, len = ref.length; i < len; i++) {
    line = ref[i];
    if (nonEmpty(line) && !isComment(line)) {
      lLines.push(line);
    }
  }
  return lLines.join("\n");
};

// ---------------------------------------------------------------------------
export var markdownify = function(block) {
  var html, result;
  debug("enter markdownify()", block);
  assert(block != null, "markdownify(): block is undef");
  if (!convert) {
    debug("return original text from markdownify() - not converting");
    return block;
  }
  html = marked.parse(undented(stripComments(block)), {
    grm: true,
    headerIds: false
  });
  debug("marked returned", html);
  result = svelteHtmlEsc(html);
  debug("return from markdownify()", result);
  return result;
};
