// Generated by CoffeeScript 2.7.0
  // Scope.coffee
import {
  LOG
} from '@jdeighan/exceptions';

import {
  undef,
  deepCopy
} from '@jdeighan/coffee-utils';

// ---------------------------------------------------------------------------
export var Scope = class Scope {
  constructor(name = undef, lSymbols = undef) {
    this.name = name;
    if (lSymbols === undef) {
      this.lSymbols = [];
    } else {
      this.lSymbols = deepCopy(lSymbols);
    }
  }

  // ..........................................................
  add(symbol) {
    if (!this.lSymbols.includes(symbol)) {
      this.lSymbols.push(symbol);
    }
  }

  // ..........................................................
  has(symbol) {
    return this.lSymbols.includes(symbol);
  }

  // ..........................................................
  dump() {
    var i, len, ref, symbol;
    ref = this.lSymbols;
    for (i = 0, len = ref.length; i < len; i++) {
      symbol = ref[i];
      LOG(`      ${symbol}`);
    }
  }

};
