// Generated by CoffeeScript 2.7.0
  // TraceWalker.coffee
import {
  assert,
  error,
  croak
} from '@jdeighan/unit-tester/utils';

import {
  undef,
  defined,
  OL
} from '@jdeighan/coffee-utils';

import {
  arrayToBlock
} from '@jdeighan/coffee-utils/block';

import {
  TreeWalker
} from '@jdeighan/mapper/tree';

// ---------------------------------------------------------------------------
export var TraceWalker = class TraceWalker extends TreeWalker {
  // ..........................................................
  //     builds a trace of the tree
  //        which is returned by endWalk()
  beginWalk() {
    this.lTrace = ["BEGIN WALK"]; // an array of strings
  }

  // ..........................................................
  visit(hNode, hUser, lStack) {
    var level, uobj;
    ({uobj, level} = hNode);
    this.lTrace.push(`VISIT     ${level} ${OL(uobj)}`);
  }

  // ..........................................................
  endVisit(hNode, hUser, lStack) {
    var level, uobj;
    ({uobj, level} = hNode);
    this.lTrace.push(`END VISIT ${level} ${OL(uobj)}`);
  }

  // ..........................................................
  visitSpecial(type, hNode, hUser, lStack) {
    var level, uobj;
    ({uobj, level} = hNode);
    this.lTrace.push(`VISIT     ${level} ${OL(uobj)} (${type})`);
  }

  // ..........................................................
  endVisitSpecial(type, hNode, hUser, lStack) {
    var level, uobj;
    ({uobj, level} = hNode);
    this.lTrace.push(`END VISIT ${level} ${OL(uobj)} (${type})`);
  }

  // ..........................................................
  endWalk() {
    var block;
    this.lTrace.push("END WALK");
    block = arrayToBlock(this.lTrace);
    this.lTrace = undef;
    return block;
  }

};
