// Generated by CoffeeScript 2.5.1
  // TreeWalker.coffee
import {
  say,
  pass,
  undef,
  error,
  warn,
  isString
} from '@jdeighan/coffee-utils';

import {
  debug
} from '@jdeighan/coffee-utils/debug';

import {
  indentStr
} from '@jdeighan/coffee-utils/indent';

import {
  Getter
} from '@jdeighan/string-input/get';

// ---------------------------------------------------------------------------
export var TreeWalker = class TreeWalker {
  walk(tree) {
    var getter;
    debug("enter walk()");
    getter = new Getter(tree);
    this.procNodes(getter, 0);
    debug("return from walk()");
  }

  procNodes(getter, level = 0) {
    var body, hNode, lineNum, node;
    debug("enter procNodes()");
    while (hNode = getter.get()) {
      ({lineNum, node, body} = hNode);
      this.visit(node, body, lineNum, getter, level);
    }
    debug("return from procNodes()");
  }

  visit(node, body, lineNum, getter, level) {}

};

// ---------------------------------------------------------------------------
export var TreePrinter = class TreePrinter extends TreeWalker {
  constructor() {
    super();
    this.lLines = [];
  }

  visit(node, body, lineNum, getter, level) {
    assert(isString(node), "TreePrinter: node is not a string");
    this.lLines.push(indentStr(node, level));
  }

  get() {
    return this.lLines.join('\n');
  }

};
