// Generated by CoffeeScript 2.7.0
// utils.coffee

// ---------------------------------------------------------------------------
export var isHashComment = function(line) {
  return line.match(/^\s*\#($|\s)/);
};
